able to start correct per docker
ttulka/LWN-Simulator pull request #3
Opened 2023-03-28 07:11 UTC by MJam9

2023-03-28 08:26 UTC, ttulka requested changes

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/devices.json
> +			"nwkSKey": "9f7772d29354d07a7e9d51979ba7d214",
diese drei auch als parameter, mit default werten die auch klar test-werte sind (000000000...) oder sowas

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/devices.json
> +					"fport": 2,
auch als parameter

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/devices.json
> +				"mtype": "ConfirmedDataUp",
auch als parameter

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/devices.json
> +				"dataRate": 0,
auch als parameter

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/devices.json
> +				"region": 1,
was heisst es hier? region waere schon interessant fuer uns, aber guck bitte noch was man hier einstellen kann (frequences?)

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/devices.json
> +						"freqUplink": 868100000,
auch als parameter

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/devices.json
> +						"freqDownlink": 868100000,
auch als parameter

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/devices.json
> +						"minDR": 0,
auch als parameter

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/devices.json
> +						"maxDR": 5
auch als parameter

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/devices.json
> +					"dataRate": 0
auch als parameter

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/devices.json
> +						"freqUplink": 0,
auch als parameter

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/devices.json
> +						"freqDownlink": 869525000,
auch als parameter

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/devices.json
> +						"enableUplink": false,
was heisst das? ich wuerde eh TRUE erwarten, kannst du das bitte herausfinden?

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/gateways.json
> +			"name": "Virtual GW",
auch als parameter

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/gateways.json
> +			"typeGateway": false,
was heisst es?

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/simulator.json
> +	"bridgeAddress": "%SIM_BRIDGE_ADDRESS%"
auf HOST und POST verteilen:

"bridgeAddress": "%BRIDGE_HOST%:%BRIDGE_PORT%"

2023-03-28 08:26 UTC, ttulka commented on docker/setup.sh
> +bridgeAddress=${SIM_BRIDGE_ADDRESS:-"172.17.0.1:1700"}
HOST und PORT

2023-03-28 08:26 UTC, ttulka commented on docker/lwnsimulatordata/devices.json
> +			"name": "Virtual Sensor",
auch als parameter

2023-03-28 08:26 UTC, ttulka commented on docker/setup.sh
> +devAddr=${DEV_ADDR:-"00be1557"}
default mehr test-messig? 00000001 oder so?

2023-03-28 08:26 UTC, ttulka commented on docker/setup.sh
> +macAddress=${GW_MAC_ADDRESSE:-"0000000000000002"}
0000000000000002 -> 1000000000000000
GW_ -> GTW_

2023-03-28 08:26 UTC, ttulka commented on docker/setup.sh
> +sed -i s/%SIM_BRIDGE_ADDRESS%/$bridgeAddress/g lwnsimulatordata/simulator.json
HOST + PORT

2023-03-28 08:26 UTC, ttulka commented on docker/setup.sh
> +sed -i s/%GW_MAC_ADDRESSE%/$macAddress/g lwnsimulatordata/gateways.json
GTW

2023-03-29 13:30 UTC, MJam9 commented
change parts

2023-03-29 14:08 UTC, ttulka approved these changes

2023-03-29 14:09 UTC, merged